{{- /*
  Load each policy YAML from files/, patch `validationFailureAction`, and emit valid YAML.
*/ -}}

{{- $files := .Files.Glob "files/*.yaml" }}
{{- range $path, $content := $files }}
{{- $policy := $content | toString }}
{{- $patched := regexReplaceAll "(?m)^([[:space:]]*)validationFailureAction:.*$" $policy (printf "${1}validationFailureAction: \"%s\"" $.Values.validationFailureAction) }}
# Source: {{ $path }}
{{ $patched | nindent 0 }}
---
{{- end }}