apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-image-registries
  annotations:
    policies.kyverno.io/title: Restrict Image Registries
    policies.kyverno.io/category: Best Practices, EKS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.26"
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Images from unknown, public registries can be of dubious quality and may not be
      scanned and secured, representing a high degree of risk. Requiring use of known, approved
      registries helps reduce threat exposure by ensuring image pulls only come from them. This
      policy validates that container images only originate from the configured allowed registries.
      Use of this policy requires customization to define your allowable registries via Helm values.
spec:
  validationFailureAction: {{ .Values.validationFailureAction | quote }}
  background: true
  rules:
  - name: validate-registries
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Unknown image registry. Allowed registries: {{ if .Values.imageRegistries.ephemeralContainers }}{{ .Values.imageRegistries.ephemeralContainers }}{{ else if .Values.imageRegistries.global }}{{ .Values.imageRegistries.global }}{{ else }}{{ .Values.allowedRegistries }}{{ end }} for ephemeralContainers, {{ if .Values.imageRegistries.initContainers }}{{ .Values.imageRegistries.initContainers }}{{ else if .Values.imageRegistries.global }}{{ .Values.imageRegistries.global }}{{ else }}{{ .Values.allowedRegistries }}{{ end }} for initContainers, {{ if .Values.imageRegistries.containers }}{{ .Values.imageRegistries.containers }}{{ else if .Values.imageRegistries.global }}{{ .Values.imageRegistries.global }}{{ else }}{{ .Values.allowedRegistries }}{{ end }} for containers"
      pattern:
        spec:
          =(ephemeralContainers):
          - image: "{{ if .Values.imageRegistries.ephemeralContainers }}{{ .Values.imageRegistries.ephemeralContainers }}{{ else if .Values.imageRegistries.global }}{{ .Values.imageRegistries.global }}{{ else }}{{ .Values.allowedRegistries }}{{ end }}"
          =(initContainers):
          - image: "{{ if .Values.imageRegistries.initContainers }}{{ .Values.imageRegistries.initContainers }}{{ else if .Values.imageRegistries.global }}{{ .Values.imageRegistries.global }}{{ else }}{{ .Values.allowedRegistries }}{{ end }}"
          containers:
          - image: "{{ if .Values.imageRegistries.containers }}{{ .Values.imageRegistries.containers }}{{ else if .Values.imageRegistries.global }}{{ .Values.imageRegistries.global }}{{ else }}{{ .Values.allowedRegistries }}{{ end }}"