name: Update Kyverno Policies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2 AM UTC

jobs:
  update-policies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Download latest Kyverno policies
        run: |
          chmod +x ./scripts/download-policies.sh
          ./scripts/download-policies.sh

      - name: Check if policies changed
        id: check_changes
        run: |
          git add charts/dynamic-policies/files/
          if git diff --cached --quiet; then
            echo "No policy changes detected."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Policy changes detected."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Bump Helm chart version if changes exist
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          CHART_FILE="charts/dynamic-policies/Chart.yaml"
          if [ ! -f "$CHART_FILE" ]; then
            echo "❌ Chart.yaml not found at $CHART_FILE"
            exit 1
          fi
          CURRENT_VERSION=$(grep '^version:' "$CHART_FILE" | awk '{print $2}')
          NEXT_VERSION=$(echo "$CURRENT_VERSION" | awk -F. -v OFS=. '{$NF += 1; print}')
          echo "Bumping chart version from $CURRENT_VERSION to $NEXT_VERSION"
          sed -i "s/^version: .*/version: $NEXT_VERSION/" "$CHART_FILE"

      - name: Package updated Helm chart
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          mkdir -p docs
          # Lint the chart with the new image registry configuration
          helm lint charts/dynamic-policies --values charts/dynamic-policies/values.yaml
          VERSION=$(grep '^version:' charts/dynamic-policies/Chart.yaml | awk '{print $2}')
          helm package charts/dynamic-policies --version "$VERSION" -d docs/
          helm repo index docs/ --url https://nirmata.github.io/kyverno-policy-helm-chart

      - name: Test chart installation with different configurations
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          # Test basic installation
          helm template test-basic charts/dynamic-policies > /dev/null
          echo "✅ Basic chart template test passed"
          
          # Test with custom image registries (YAML list format)
          helm template test-custom charts/dynamic-policies \
            --set imageRegistries.global[0]="docker.io/*" \
            --set imageRegistries.global[1]="gcr.io/*" \
            --set imageRegistries.initContainers[0]="docker.io/*" \
            --set imageRegistries.initContainers[1]="gcr.io/*" \
            --set imageRegistries.initContainers[2]="quay.io/*" \
            --set validationFailureAction=Enforce > /dev/null
          echo "✅ Custom image registry configuration test passed"
          
          # Test with legacy allowedRegistries setting
          helm template test-legacy charts/dynamic-policies \
            --set allowedRegistries="docker.io/* | gcr.io/*" > /dev/null
          echo "✅ Legacy configuration test passed"

      - name: Commit and push updated chart and policies
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git add charts/dynamic-policies/files/ charts/dynamic-policies/Chart.yaml docs/
          git commit -m "Update Kyverno policies and bump chart version

          - Updated restrict_image_registries policy with configurable image registries
          - Added support for YAML list format for image registry configuration
          - Added support for individual container type registry configuration
          - Maintained backward compatibility with allowedRegistries setting
          - Updated chart version to $VERSION"
          git push