name: Update Kyverno Policies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2 AM UTC

jobs:
  update-policies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Download latest Kyverno policies
        run: |
          chmod +x ./scripts/download-policies.sh
          ./scripts/download-policies.sh

      - name: Check if policies changed
        id: check_changes
        run: |
          git add charts/dynamic-policies/files/
          if git diff --cached --quiet; then
            echo "No policy changes detected."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Policy changes detected."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Bump Helm chart version if changes exist
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          CHART_FILE="charts/dynamic-policies/Chart.yaml"
          if [ ! -f "$CHART_FILE" ]; then
            echo "❌ Chart.yaml not found at $CHART_FILE"
            exit 1
          fi
          CURRENT_VERSION=$(grep '^version:' "$CHART_FILE" | awk '{print $2}')
          NEXT_VERSION=$(echo "$CURRENT_VERSION" | awk -F. -v OFS=. '{$NF += 1; print}')
          echo "Bumping chart version from $CURRENT_VERSION to $NEXT_VERSION"
          sed -i "s/^version: .*/version: $NEXT_VERSION/" "$CHART_FILE"

      - name: Package updated Helm chart
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          mkdir -p docs
          helm lint charts/dynamic-policies
          helm package charts/dynamic-policies
          mv kyverno-policies-*.tgz docs/
          helm repo index docs --url https://nirmata.github.io/kyverno-policy-helm-chart

      - name: Commit and push updated chart and policies
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git add dynamic-policies/ charts/dynamic-policies/Chart.yaml docs/
          git commit -m "Update Kyverno policies and bump chart version"
          git push
